version: '3.8'
services:
  hrl-airflow:
    image: apache/airflow:2.9.1
    user: root
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__RBAC=True
    volumes:
      - ..:/workspace
      - ./webserver_config.py:/opt/airflow/webserver_config.py
    working_dir: /workspace
    command: ["bash", "/workspace/install.sh"]
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - airflow-net

  kafka:
    image: bitnami/kafka:3
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    networks:
      - airflow-net
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - airflow-net

networks:
  airflow-net:
